import 'package:stratum_ui/src/src.dart';

extension SvgExtension on SvgGenImage {
  SvgPicture svgIcon({
    Key? key,
    bool matchTextDirection = false,
    AssetBundle? bundle,
    String? package = 'design_system',
    double? size,
    BoxFit fit = BoxFit.contain,
    AlignmentGeometry alignment = Alignment.center,
    bool allowDrawingOutsideViewBox = false,
    WidgetBuilder? placeholderBuilder,
    String? semanticsLabel,
    bool excludeFromSemantics = false,
    SvgTheme theme = const SvgTheme(),
    ColorFilter? colorFilter,
    Color? color,
    Clip clipBehavior = Clip.hardEdge,
  }) =>
      SvgPicture.asset(
        path,
        key: key,
        matchTextDirection: matchTextDirection,
        bundle: bundle,
        package: package,
        width: size,
        height: size,
        fit: fit,
        alignment: alignment,
        allowDrawingOutsideViewBox: allowDrawingOutsideViewBox,
        placeholderBuilder: placeholderBuilder,
        semanticsLabel: semanticsLabel,
        excludeFromSemantics: excludeFromSemantics,
        theme: theme,
        colorFilter: color != null
            ? ColorFilter.mode(color, BlendMode.srcIn)
            : colorFilter,
        clipBehavior: clipBehavior,
      );

  AppIcon icon({
    Key? key,
    bool matchTextDirection = false,
    AssetBundle? bundle,
    String? package,
    WidgetSize size = WidgetSize.md,
    double? customSize,
    BoxFit fit = BoxFit.contain,
    AlignmentGeometry alignment = Alignment.center,
    bool allowDrawingOutsideViewBox = false,
    AppIconWidgetBuilder? loadingBuilder,
    AppIconWidgetBuilder? placeholderBuilder,
    AppIconWidgetErrorBuilder? errorBuilder,
    String? semanticsLabel,
    bool excludeFromSemantics = false,
    SvgTheme theme = const SvgTheme(),
    ColorEnum? color,
    Color? customColor,
    BlendMode? colorBlendMode,
    Clip clipBehavior = Clip.hardEdge,
  }) =>
      AppIcon(
        key: key,
        path: path,
        matchTextDirection: matchTextDirection,
        bundle: bundle,
        package: package,
        size: size,
        customSize: customSize,
        fit: fit,
        alignment: alignment,
        allowDrawingOutsideViewBox: allowDrawingOutsideViewBox,
        loadingBuilder: loadingBuilder,
        placeholderBuilder: placeholderBuilder,
        errorBuilder: errorBuilder,
        semanticLabel: semanticsLabel,
        excludeFromSemantics: excludeFromSemantics,
        svgTheme: theme,
        color: color,
        customColor: customColor,
        colorBlendMode: colorBlendMode,
        clipBehavior: clipBehavior,
      );
}
